name: Run WDIO Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: test
      BRAND: gfa
      ANDROID_HOME: /usr/local/lib/android/sdk
      PATH: $PATH:/usr/local/lib/android/sdk/platform-tools:/usr/local/lib/android/sdk/tools

    steps:
    - name: Install tar
      run: apt-get update && apt-get install -y tar

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: |
        npm install
        npm install -g appium
        appium driver install uiautomator2  # Instalar UiAutomator2 para Android

    - name: Install Android SDK
      run: |
        apt-get update
        apt-get install -y openjdk-11-jdk wget unzip
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        mkdir -p /usr/local/lib/android/sdk/cmdline-tools
        unzip -q cmdline-tools.zip -d /usr/local/lib/android/sdk/cmdline-tools
        rm cmdline-tools.zip
        yes | /usr/local/lib/android/sdk/cmdline-tools/bin/sdkmanager --licenses
        /usr/local/lib/android/sdk/cmdline-tools/bin/sdkmanager "platform-tools" "emulator" "platforms;android-33" "build-tools;33.0.0"

    - name: Start Appium Server
      run: |
        appium --log-level info --port 4723 &
        sleep 20  # Asegura tiempo suficiente para que Appium arranque

    - name: Run WDIO Tests
      run: npm run wdio

    - name: Upload Allure Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: allure-results
        path: allure-results/
