name: Android ADB Setup

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  setup-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Android SDK
        run: |
          echo "Setting up Android SDK..."
          mkdir -p "$HOME/android-sdk/cmdline-tools"
          curl -o cmdline-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip -q cmdline-tools.zip -d "$HOME/android-sdk/cmdline-tools"
          mv "$HOME/android-sdk/cmdline-tools/cmdline-tools" "$HOME/android-sdk/cmdline-tools/latest"
          echo "export ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator:$PATH" >> $GITHUB_ENV
          source $GITHUB_ENV
          echo "Accepting licenses..."
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
          echo "Installing platform-tools..."
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools"

      - name: Verify ADB Installation
        run: |
          echo "Checking ADB installation..."
          echo "ANDROID_HOME is set to: $ANDROID_HOME"
          echo "PATH is set to: $PATH"
          ls -al $ANDROID_HOME/platform-tools
          adb version || { echo "ADB not found or not working"; exit 1; }
