name: E2E Tests with Appium and Android Emulator

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-e2e:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el repositorio
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Instalar dependencias del proyecto
      - name: Install Project Dependencies
        run: |
          npm install

      # 4. Instalar Android SDK
      - name: Install Android SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk unzip wget
          mkdir -p "$HOME/android-sdk/cmdline-tools"
          curl -o cmdline-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip -q cmdline-tools.zip -d "$HOME/android-sdk/cmdline-tools"
          mv "$HOME/android-sdk/cmdline-tools/cmdline-tools" "$HOME/android-sdk/cmdline-tools/latest"
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator:$PATH
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "system-images;android-31;default;x86_64" "emulator" "platforms;android-31"

      # 5. Crear y arrancar el emulador
      - name: Start Android Emulator
        run: |
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator:$PATH
          echo "no" | $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager create avd -n test -k "system-images;android-31;default;x86_64" --device "pixel_5"
          $ANDROID_HOME/emulator/emulator -avd test -no-audio -no-window -gpu swiftshader_indirect -accel off &
          sleep 60
          $ANDROID_HOME/platform-tools/adb wait-for-device

      # 6. Instalar Appium
      - name: Install Appium
        run: |
          npm install -g appium

      # 7. Instalar el driver UiAutomator2 en Appium
      - name: Install Appium UiAutomator2 Driver
        run: |
          npx appium driver install uiautomator2

      # 8. Iniciar el servidor Appium
      - name: Start Appium Server
        run: |
          npx appium --relaxed-security --base-path "/wd/hub" &
          sleep 5

      # 9. Validar que Appium está corriendo
      - name: Validate Appium Server
        run: |
          curl http://127.0.0.1:4723/wd/hub/status

      # 10. Ejecutar pruebas E2E
      - name: Run E2E Tests
        env:
          BRAND: gfa
        run: |
          BRAND=gfa npm run wdio
