name: Android Appium Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  android-tests:
    runs-on: ubuntu-latest

    env:
      DEVICEFARM_TEST_PACKAGE_PATH: "./" # Ajusta según el proyecto
      DEVICEFARM_LOG_DIR: "./logs" # Cambié esta variable de entorno
      DEVICEFARM_APP_PATH: "https://appsreservamos2024r1.s3.us-east-2.amazonaws.com/gfa22112024.apk" 
      DEVICEFARM_DEVICE_NAME: "Pixel_5"
      DEVICEFARM_DEVICE_PLATFORM_NAME: "Android"
      DEVICEFARM_DEVICE_OS_VERSION: "12.0"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js and Appium
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: |
          echo "Instalando Appium"
          npm install -g appium@2
          appium --version

      - name: Install dependencies
        run: |
          npm install --force --legacy-peer-deps

      - name: Install UiAutomator2 driver
        run: |
          appium driver install uiautomator2
          appium driver list --installed

      - name: Create log directory
        run: |
          mkdir -p $DEVICEFARM_LOG_DIR

      - name: Start Appium server
        run: |
          nohup appium --base-path=/wd/hub --log-timestamp \
            --log-no-colors --relaxed-security --default-capabilities \
            '{"appium:deviceName": "'$DEVICEFARM_DEVICE_NAME'", \
            "platformName": "'$DEVICEFARM_DEVICE_PLATFORM_NAME'", \
            "appium:app": "'$DEVICEFARM_APP_PATH'", \
            "appium:udid": "emulator-5554", \
            "appium:platformVersion": "'$DEVICEFARM_DEVICE_OS_VERSION'", \
            "appium:chromedriverExecutableDir": "'$DEVICEFARM_CHROMEDRIVER_EXECUTABLE_DIR'", \
            "appium:automationName": "UiAutomator2"}' \
            >> $DEVICEFARM_LOG_DIR/appium.log 2>&1 &
          sleep 10
          until curl --silent --fail "http://0.0.0.0:4723/wd/hub/status"; do
            echo "Esperando que Appium inicie...";
            sleep 1;
          done

      - name: Run tests
        run: |
          npm ls --depth=0
          npx wdio run wdio.conf.js

      - name: Upload logs
        uses: actions/upload-artifact@v3
        with:
          name: appium-logs
          path: ./logs

      - name: Upload test reports
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: ./reports
