name: Run WDIO Tests with Docker

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run Tests in Docker
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace \
          openjdk:11 bash -c "
            apt-get update &&
            apt-get install -y wget unzip tar curl &&
            wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip &&
            mkdir -p /usr/local/lib/android/sdk/cmdline-tools &&
            unzip -q cmdline-tools.zip -d /usr/local/lib/android/sdk/cmdline-tools &&
            rm cmdline-tools.zip &&
            yes | /usr/local/lib/android/sdk/cmdline-tools/bin/sdkmanager --licenses &&
            /usr/local/lib/android/sdk/cmdline-tools/bin/sdkmanager 'platform-tools' 'emulator' 'platforms;android-33' 'system-images;android-33;google_apis;x86_64' &&
            npm install &&
            npm install -g appium &&
            appium driver install uiautomator2 &&
            appium --log-level info --port 4723 &
            sleep 20 &&
            adb start-server &&
            adb devices &&
            nohup /usr/local/lib/android/sdk/emulator/emulator -avd test -no-window -no-audio &
            sleep 30 &&
            npm run wdio
          "
