name: Appium Service

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  start-appium:
    runs-on: ubuntu-latest

    steps:
      # Instalar dependencias necesarias
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Appium
        run: |
          npm install -g appium

      # Levantar Appium
      - name: Start Appium server
        run: |
          appium --relaxed-security --base-path "/wd/hub" &
          sleep 5 # Esperar a que Appium se inicie

      # Validar que Appium está corriendo
      - name: Validate Appium is running
        run: |
          curl http://127.0.0.1:4723/wd/hub/status
