name: Run Appium Tests

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        npm ci
        npm install appium --global
        appium --version

    - name: Start Appium Server
      run: |
        nohup appium --relaxed-security --base-path "/wd/hub" &
        sleep 10  # Esperar a que Appium inicie

    - name: Setup Android Emulator
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils
        sdkmanager "system-images;android-35;google_apis;x86_64"
        avdmanager create avd -n test -k "system-images;android-35;google_apis;x86_64" --force
        nohup emulator @test -no-window -no-audio &
        adb wait-for-device
        sleep 60  # Esperar a que el emulador inicie completamente

    - name: Run Tests
      run: |
        npm run wdio
