name: Android Emulator Setup and Validation for Appium

on:
  push:
    branches:
      - main

jobs:
  android-setup:
    runs-on: ubuntu-latest

    steps:
      # Clonar el repositorio
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Instalar dependencias necesarias
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk unzip wget curl

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Download APK
        run: |
          mkdir -p ./apps
          wget -O ./apps/gfa22112024.apk https://appsreservamos2024r1.s3.us-east-2.amazonaws.com/gfa22112024.apk
          ls -l ./apps/gfa22112024.apk

      # Configurar Android SDK
      - name: Setup Android SDK
        run: |
          mkdir -p "$HOME/android-sdk/cmdline-tools"
          curl -o cmdline-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip -q cmdline-tools.zip -d "$HOME/android-sdk/cmdline-tools"
          mv "$HOME/android-sdk/cmdline-tools/cmdline-tools" "$HOME/android-sdk/cmdline-tools/latest"
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator:$PATH" >> $GITHUB_ENV

      # Aceptar licencias y descargar componentes necesarios
      - name: Install Android SDK Components
        run: |
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator:$PATH
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-30" "system-images;android-30;default;x86_64" "emulator" "build-tools;30.0.3"


      # Validar instalación de ADB
      - name: Verify ADB Installation
        run: |
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator:$PATH
          adb version

      # Crear y arrancar el emulador
      - name: Create and Start Emulator
        run: |
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator:$PATH
          echo "no" | $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager create avd -n test -k "system-images;android-30;default;x86_64" --device "pixel_5"
          $ANDROID_HOME/emulator/emulator -avd test -no-snapshot -no-audio -no-window -gpu swiftshader_indirect -accel off -verbose &
          sleep 180

      # Esperar hasta que el emulador complete el arranque
      - name: Wait for Emulator Boot
        run: |
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator:$PATH
          adb wait-for-device
          for i in {1..60}; do
            if adb shell getprop sys.boot_completed | grep -m 1 '1'; then
              echo "Emulator boot completed"
              exit 0
            fi
            echo "Waiting for emulator to complete boot... ($i)"
            sleep 10
          done
          echo "Emulator did not complete boot in time"
          exit 1

      # Verificar que el emulador está funcionando
      - name: Verify Emulator Running
        run: |
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator:$PATH
          adb devices

      # Instalar Appium
      - name: Install Appium
        run: |
          npm install -g appium
          appium --version
          echo "Appium setup validated successfully"

      # Install Appium driver uiautomator2
      - name: Install Appium Driver
        run: |
          appium driver install uiautomator2
          echo "Install Appium driver uiautomator2"

      # Iniciar appium service
      - name: Init appium service
        run: |
          nohup appium --relaxed-security --base-path "/wd/hub" > appium.log 2>&1 &
          --log-level debug \
          --log-timestamp \
          --log-no-colors \
          --log appium.log > appium_detailed.log 2>&1 &
          echo "Appium service init"

      # Validate Appium Driver Installation
      - name: Validate Appium Driver Installation
        run: appium driver list --installed


      # Verificar el estado del servicio Appium y capturar logs en caso de fallo
      - name: Validate Appium Service Status
        run: |
          export APPIUM_URL=http://127.0.0.1:4723/wd/hub
          for i in {1..30}; do
            STATUS=$(curl -s -o /dev/null -w "%{http_code}" $APPIUM_URL/status)
            if [ "$STATUS" -eq 200 ]; then
              echo "Appium service is ready."
              exit 0
            fi
            echo "Waiting for Appium service to be ready... ($i)"
            sleep 5
          done
          echo "Appium service did not become ready in time. Logs:"
          echo "------------------ appium.log ------------------"
          cat appium.log || echo "appium.log not found"
          echo "---------------- appium_detailed.log ----------------"
          cat appium_detailed.log || echo "appium_detailed.log not found"
          exit 1
        shell: bash



      - name: Archive and Display Full Logs on Failure
        if: failure()
        run: |
          echo "Archiving logs for further analysis."
          mkdir -p logs
          mv appium.log logs/ || echo "appium.log not found for archiving."
          mv appium_detailed.log logs/ || echo "appium_detailed.log not found for archiving."
          echo "Logs archived. Displaying content:"
          echo "------------------ appium.log ------------------"
          cat logs/appium.log || echo "appium.log not available."
          echo "---------------- appium_detailed.log ----------------"
          cat logs/appium_detailed.log || echo "appium_detailed.log not available."
        shell: bash



      # Instalar appium-doctor
      #- name: Install Appium Doctor
      #  run: |
      #    npm install -g appium-doctor
      #    appium-doctor

      # Verificar que Appium está ejecutándose
      - name: Verify Appium is Running
        run: curl http://127.0.0.1:4723/wd/hub/status || (echo "Appium failed to start" && exit 1)


      # Instalar dependencias del proyecto
      - name: Install Project Dependencies
        working-directory: . # Define la raíz como directorio de trabajo
        run: |
          npm install

      # Ejecutar pruebas E2E
      - name: Run E2E Tests
        run: |
          BRAND=gfa npm run wdio
