name: Android Appium Test Workflow

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    # 1. Configurar el entornos
    - name: Configurar Android SDK y entorno
      run: |
        export ANDROID_HOME=$HOME/android-sdk
        export PATH=$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator:$ANDROID_HOME/tools:$PATH
        adb version

    # 2. Instalar dependencias
    - name: Instalar dependencias del proyecto
      run: |
        npm install

    # 3. Descargar imagen ARM del emulador y crear AVD
    - name: Configurar emulador Android
      run: |
        sdkmanager "system-images;android-31;default;arm64-v8a"
        avdmanager create avd -n test -k "system-images;android-31;default;arm64-v8a"
        emulator -avd test -no-window -no-audio &

    # 4. Verificar que ADB reconozca el emulador
    - name: Verificar emulador Android
      run: |
        adb devices

    # 5. Instalar Appium
    - name: Instalar Appium
      run: |
        npm install -g appium
        adb start-server
        npx appium --relaxed-security --base-path "/wd/hub" &

    # 6. Ejecutar pruebas
    - name: Ejecutar pruebas con WebDriverIO
      run: |
        npx wdio run ./wdio.conf.js
