name: Appium Test Workflow

on:
  push:
    branches:
      - main  # Ejecuta el flujo al hacer push en la rama `main`
  pull_request:
    branches:
      - main  # Ejecuta el flujo al abrir un pull request hacia la rama `main`

jobs:
  setup-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup Android SDK
        run: |
          mkdir -p "$HOME/android-sdk/cmdline-tools"
          curl -o cmdline-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip -q cmdline-tools.zip -d "$HOME/android-sdk/cmdline-tools"
          mv "$HOME/android-sdk/cmdline-tools/cmdline-tools" "$HOME/android-sdk/cmdline-tools/latest"
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator:$PATH
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "system-images;android-31;default;x86_64" "emulator" "platforms;android-31"
          if [ ! -f "$ANDROID_HOME/platform-tools/adb" ]; then
              echo "adb no está instalado correctamente. Revisa sdkmanager."
              exit 1
          fi

      - name: Validate adb Installation
        run: |
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator:$PATH
          adb version || { echo "ADB no encontrado en PATH"; exit 1; }

      - name: Create and Start Emulator
        run: |
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator:$PATH
          echo "no" | $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager create avd -n test -k "system-images;android-31;default;x86_64" --device "pixel_5"
          $ANDROID_HOME/emulator/emulator -avd test -no-audio -no-window -gpu swiftshader_indirect -accel off &
          sleep 60
          $ANDROID_HOME/platform-tools/adb wait-for-device

      - name: Install Appium
        run: |
          npm install -g appium
          npx appium driver install uiautomator2

      - name: Start Appium server
        run: |
          npx appium --relaxed-security --base-path "/wd/hub" &
          sleep 5
          curl http://127.0.0.1:4723/wd/hub/status

      - name: Run Appium Tests
        run: |
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator:$PATH
          npm install
          BRAND=gfa npm run wdio
