name: Setup Android SDK and AVD

on:
  push:
    branches:
      - main

jobs:
  setup-android:
    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Install Android SDK
      run: |
        mkdir -p $HOME/android-sdk
        echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
        echo "PATH=$ANDROID_HOME/emulator:$ANDROID_HOME/platform-tools:$ANDROID_HOME/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV
        sudo apt-get update
        sudo apt-get install -y unzip wget
        wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O cmdline-tools.zip
        mkdir -p $ANDROID_HOME/cmdline-tools
        unzip cmdline-tools.zip -d $ANDROID_HOME/cmdline-tools
        mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
        rm cmdline-tools.zip

    - name: Install System Images and Create AVD
      run: |
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-31" "system-images;android-31;default;x86_64" "emulator"
        echo "no" | $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager create avd -n test -k "system-images;android-31;default;x86_64" --device "pixel"

    - name: Start Emulator
      run: |
        $ANDROID_HOME/emulator/emulator -avd test -no-snapshot -no-window &
        adb wait-for-device
        adb devices
