name: Run WDIO Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: test
      BRAND: gfa
      ANDROID_HOME: /usr/local/lib/android/sdk
      PATH: $PATH:/usr/local/lib/android/sdk/platform-tools:/usr/local/lib/android/sdk/cmdline-tools/latest/bin

    steps:
    - name: Install required tools
      run: |
        apt-get update
        apt-get install -y tar openjdk-11-jdk wget unzip curl

    - name: Install Android SDK
      run: |
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        mkdir -p /usr/local/lib/android/sdk/cmdline-tools
        unzip -q cmdline-tools.zip -d /usr/local/lib/android/sdk/cmdline-tools
        rm cmdline-tools.zip
        yes | /usr/local/lib/android/sdk/cmdline-tools/bin/sdkmanager --licenses
        /usr/local/lib/android/sdk/cmdline-tools/bin/sdkmanager "platform-tools" "emulator" "platforms;android-33" "system-images;android-33;google_apis;x86_64"

    - name: Setup Android Emulator
      run: |
        /usr/local/lib/android/sdk/emulator/emulator -list-avds || /usr/local/lib/android/sdk/cmdline-tools/bin/avdmanager create avd -n test -k "system-images;android-33;google_apis;x86_64"
        nohup /usr/local/lib/android/sdk/emulator/emulator -avd test -no-window -no-audio &

    - name: Wait for Android Emulator to start
      run: adb wait-for-device

    - name: Install Node.js dependencies
      run: |
        npm install
        npm install -g appium
        appium driver install uiautomator2

    - name: Start Appium Server
      run: |
        appium --log-level info --port 4723 &
        sleep 20  # Espera a que el servidor esté listo

    - name: Run WDIO Tests
      run: npm run wdio

    - name: Upload Allure Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: allure-results
        path: allure-results/
