name: Android Emulator Setup

on:
  push:
    branches:
      - main

jobs:
  android-setup:
    runs-on: ubuntu-latest

    steps:
      # Instalar dependencias necesarias
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk unzip wget

      # Configurar Android SDK
      - name: Setup Android SDK
        run: |
          mkdir -p "$HOME/android-sdk/cmdline-tools"
          curl -o cmdline-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip -q cmdline-tools.zip -d "$HOME/android-sdk/cmdline-tools"
          mv "$HOME/android-sdk/cmdline-tools/cmdline-tools" "$HOME/android-sdk/cmdline-tools/latest"
          echo "export ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator:$PATH" >> $GITHUB_ENV
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
          $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "system-images;android-31;default;x86_64" "emulator" "platforms;android-31"

      # Verificar instalación de ADB
      - name: Verify ADB Installation
        run: adb version

      # Crear y arrancar el emulador
      - name: Create and Start Emulator
        run: |
          echo "no" | $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager create avd -n test -k "system-images;android-31;default;x86_64" --device "pixel_5"
          $ANDROID_HOME/emulator/emulator -avd test -no-snapshot -no-audio -no-window -gpu swiftshader_indirect -accel off -verbose &
          sleep 180

      # Esperar hasta que el emulador complete el arranque
      - name: Wait for Emulator Boot
        run: |
          adb wait-for-device
          for i in {1..60}; do
            if adb shell getprop sys.boot_completed | grep -m 1 '1'; then
              echo "Emulator boot completed"
              exit 0
            fi
            echo "Waiting for emulator to complete boot... ($i)"
            sleep 10
          done
          echo "Emulator did not complete boot in time"
          exit 1

      # Verificar que el emulador está funcionando
      - name: Verify Emulator Running
        run: adb devices

      # Configurar proyecto Node.js
      - name: Setup Node.js Environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Instalar dependencias
      - name: Install Project Dependencies
        run: yarn install

      # Ejecutar pruebas con WebDriverIO
      - name: Run Tests
        run: BRAND=gfa yarn wdio
        env:
          ANDROID_HOME: ${{ env.ANDROID_HOME }}
          PATH: ${{ env.PATH }}
