name: Run Appium Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Appium
        run: npm install -g appium

      - name: Set up Android SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk wget unzip
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          mkdir -p $HOME/android-sdk
          unzip -q commandlinetools-linux-9477386_latest.zip -d $HOME/android-sdk/cmdline-tools
          mv $HOME/android-sdk/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator:$PATH
          sdkmanager --sdk_root=$ANDROID_HOME --licenses
          sdkmanager --sdk_root=$ANDROID_HOME "platform-tools" "emulator" "system-images;android-31;default;x86_64"

      - name: Start Appium server
        run: nohup appium --relaxed-security --base-path "/wd/hub" &

      - name: Start Android Emulator
        run: |
          echo "no" | avdmanager create avd -n Pixel_7_API_31 -k "system-images;android-31;default;x86_64"
          nohup emulator -avd Pixel_7_API_31 -no-window -no-audio &

      - name: Wait for emulator to boot
        run: |
          adb wait-for-device
          adb shell input keyevent 82

      - name: Install dependencies
        run: npm ci

      - name: Run WebDriverIO Tests
        run: BRAND=gfa npm run wdio
